<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>James Routley | Feed</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="../styles.css"
      media="screen"
    />
  </head>
  <body>
    <a href="/index.html">Back</a>
    <a href="https://pythonspeed.com/articles/numba-profiling/">Original</a>
    <h1>Profiling your Numba code</h1>
    
    <div id="readability-page-1" class="page"><div itemprop="articleBody">
      

<p>If you’re writing numeric Python code, <a href="http://ablwr.github.io/articles/numba-faster-python/">Numba</a> can be a great way to speed up your program.
By compiling a subset of Python to machine code, Numba lets you write for loops and other constructs that would be too slow in normal Python.
In other words, it’s similar to Cython, C, or Rust, in that it lets you write compiled extensions for Python.</p>

<p>Numba code isn’t always as fast as it could be, however.
This is where profiling is useful: it can find at least some of the bottlenecks in your code.</p>

<p>In this article we’ll cover:</p>

<ul>
  <li>Profila, a new profiler I’ve released that is specifically designed for Numba code.</li>
  <li>The limits of profiling.
There are many potential performance enhancements that a profiler can’t and won’t help you discover.</li>
</ul>

<!-- TEASER_END -->

<h2 id="introducing-profila-a-profiler-for-numba">Introducing Profila: a profiler for Numba</h2>

<p><a href="https://github.com/pythonspeed/profila">Profila</a> is a profiler specifically designed to identify which lines of code in your Numba code are slow.
It works via sampling: it runs a <code>gdb</code> process that connects to your process every 10ms or so, gets a backtrace, and uses that to identify which lines of code were running.
Get enough samples, and you’ll get a sense of where the most time was spent in your program.</p>

<p>Let’s see Profila in action!
We’re going to profile the following program, which dithers an image, switching it from grayscale to black and white.
(This is the initial naive version that I then <a href="http://ablwr.github.io/articles/optimizing-dithering/">optimized for performance in a different article</a>.)</p>

<div><div><pre><code><span>from</span> <span>numba</span> <span>import</span> <span>njit</span>
<span>import</span> <span>numpy</span> <span>as</span> <span>np</span>
<span>from</span> <span>skimage</span> <span>import</span> <span>io</span>
<span>from</span> <span>time</span> <span>import</span> <span>time</span>

<span>IMAGE</span> <span>=</span> <span>io</span><span>.</span><span>imread</span><span>(</span><span>&#34;hallway.jpg&#34;</span><span>)</span>

<span># Code that is decorated with numba.njit looks like Python code,
# but is actually compiled into machine code, at runtime. This
# is fast, low-level code!
</span><span>@</span><span>njit</span>
<span>def</span> <span>dither</span><span>(</span><span>img</span><span>):</span>
    <span># Allow negative values and wider range than a uint8 has:
</span>    <span>result</span> <span>=</span> <span>img</span><span>.</span><span>astype</span><span>(</span><span>np</span><span>.</span><span>int16</span><span>)</span>
    <span>y_size</span> <span>=</span> <span>img</span><span>.</span><span>shape</span><span>[</span><span>0</span><span>]</span>
    <span>x_size</span> <span>=</span> <span>img</span><span>.</span><span>shape</span><span>[</span><span>1</span><span>]</span>
    <span>last_y</span> <span>=</span> <span>y_size</span> <span>-</span> <span>1</span>
    <span>last_x</span> <span>=</span> <span>x_size</span> <span>-</span> <span>1</span>
    <span>for</span> <span>y</span> <span>in</span> <span>range</span><span>(</span><span>y_size</span><span>):</span>
        <span>for</span> <span>x</span> <span>in</span> <span>range</span><span>(</span><span>x_size</span><span>):</span>
            <span>old_value</span> <span>=</span> <span>result</span><span>[</span><span>y</span><span>,</span> <span>x</span><span>]</span>
            <span>if</span> <span>old_value</span> <span>&lt;</span> <span>0</span><span>:</span>
                <span>new_value</span> <span>=</span> <span>0</span>
            <span>elif</span> <span>old_value</span> <span>&gt;</span> <span>255</span><span>:</span>
                <span>new_value</span> <span>=</span> <span>255</span>
            <span>else</span><span>:</span>
                <span>new_value</span> <span>=</span> <span>np</span><span>.</span><span>uint8</span><span>(</span><span>np</span><span>.</span><span>round</span><span>(</span><span>old_value</span> <span>/</span> <span>255.0</span><span>))</span> <span>*</span> <span>255</span>
            <span>result</span><span>[</span><span>y</span><span>,</span> <span>x</span><span>]</span> <span>=</span> <span>new_value</span>
            <span># We might get a negative value for the error:
</span>            <span>error</span> <span>=</span> <span>np</span><span>.</span><span>int16</span><span>(</span><span>old_value</span><span>)</span> <span>-</span> <span>new_value</span>
            <span>if</span> <span>x</span> <span>&lt;</span> <span>last_x</span><span>:</span>
                <span>result</span><span>[</span><span>y</span><span>,</span> <span>x</span> <span>+</span> <span>1</span><span>]</span> <span>+=</span> <span>error</span> <span>*</span> <span>7</span> <span>//</span> <span>16</span>
            <span>if</span> <span>y</span> <span>&lt;</span> <span>last_y</span> <span>and</span> <span>x</span> <span>&gt;</span> <span>0</span><span>:</span>
                <span>result</span><span>[</span><span>y</span> <span>+</span> <span>1</span><span>,</span> <span>x</span> <span>-</span> <span>1</span><span>]</span> <span>+=</span> <span>error</span> <span>*</span> <span>3</span> <span>//</span> <span>16</span>
            <span>if</span> <span>y</span> <span>&lt;</span> <span>last_y</span><span>:</span>
                <span>result</span><span>[</span><span>y</span> <span>+</span> <span>1</span><span>,</span> <span>x</span><span>]</span> <span>+=</span> <span>error</span> <span>*</span> <span>5</span> <span>//</span> <span>16</span>
            <span>if</span> <span>y</span> <span>&lt;</span> <span>last_y</span> <span>and</span> <span>x</span> <span>&lt;</span> <span>last_x</span><span>:</span>
                <span>result</span><span>[</span><span>y</span> <span>+</span> <span>1</span><span>,</span> <span>x</span> <span>+</span> <span>1</span><span>]</span> <span>+=</span> <span>error</span> <span>//</span> <span>16</span>

    <span>return</span> <span>result</span><span>.</span><span>astype</span><span>(</span><span>np</span><span>.</span><span>uint8</span><span>)</span>

<span># Run a first time, to compile the code:
</span><span>dither</span><span>(</span><span>IMAGE</span><span>)</span>

<span># Make sure we run this for long enough that the profiler
# gets sufficient samples:
</span><span>start</span> <span>=</span> <span>time</span><span>()</span>
<span>runs</span> <span>=</span> <span>0</span>
<span>while</span> <span>time</span><span>()</span> <span>-</span> <span>start</span> <span>&lt;</span> <span>5</span><span>:</span>
    <span>runs</span> <span>+=</span> <span>1</span>
    <span>dither</span><span>(</span><span>IMAGE</span><span>)</span>

<span>elapsed</span> <span>=</span> <span>time</span><span>()</span> <span>-</span> <span>start</span>
<span>print</span><span>(</span><span>f</span><span>&#34;Processed </span><span>{</span><span>int</span><span>(</span><span>round</span><span>(</span><span>runs</span> <span>/</span> <span>elapsed</span><span>))</span><span>}</span><span> images / sec&#34;</span><span>)</span>
</code></pre></div></div>

<p>We then install <code>gdb</code> and <code>profila</code>:</p>

<div><div><pre><code>$ sudo apt-get install -y gdb
$ pip install profila
</code></pre></div></div>

<p>And now we can use Profila to profile the code:</p>

<div><div><pre><code>$ python -m profila annotate -- dither.py
Processed 255 images / sec
# Total samples: 805 (37.8% non-Numba samples, 1.9% bad samples)

## File `dither.py`
Lines 14 to 40:

  0.1% |     result = img.astype(np.int16)
       |     y_size = img.shape[0]
       |     x_size = img.shape[1]
       |     last_y = y_size - 1
       |     last_x = x_size - 1
       |     for y in range(y_size):
  0.2% |         for x in range(x_size):
       |             old_value = result[y, x]
       |             if old_value &lt; 0:
       |                 new_value = 0
  1.0% |             elif old_value &gt; 255:
       |                 new_value = 255
       |             else:
 30.2% |                 new_value = np.uint8(np.round(old_value / 255.0)) * 255
       |             result[y, x] = new_value
       |             # We might get a negative value for the error:
  2.0% |             error = np.int16(old_value) - new_value
  0.6% |             if x &lt; last_x:
 11.3% |                 result[y, x + 1] += error * 7 // 16
       |             if y &lt; last_y and x &gt; 0:
  0.9% |                 result[y + 1, x - 1] += error * 3 // 16
       |             if y &lt; last_y:
  2.4% |                 result[y + 1, x] += error * 5 // 16
       |             if y &lt; last_y and x &lt; last_x:
  1.6% |                 result[y + 1, x + 1] += error // 16
       |
  0.2% |     return result.astype(np.uint8)

## File `numba/np/arraymath.py`
Lines 3157 to 3157:

  9.8% |                         return _np_round_float(a)
</code></pre></div></div>

<h3 id="optimizing-the-code">Optimizing the code</h3>

<p>First, notice from the top of the output that 37.8 + 1.9 = about 40% of the samples were either bad, or not running Numba code.
This includes time spent importing modules, running regular Python code, compiling the Numba code, and so on.
That means 60% of the time was spent running actual Numba code.</p>

<p>Then, we can see the combination of <code>np.round()</code> and <code>new_value = np.uint8(np.round(old_value / 255.0)) * 255</code> is 30.2 + 9.8 = 40% of total samples.
So that means 40/60, two thirds of the time, was spent in that one line of code, turning <code>old_value</code> into <code>new_value</code>.</p>

<p>As we saw in <a href="http://ablwr.github.io/articles/optimizing-dithering/">the original article</a> featuring this example, we can replace this code:</p>

<div><div><pre><code><span>if</span> <span>old_value</span> <span>&lt;</span> <span>0</span><span>:</span>
    <span>new_value</span> <span>=</span> <span>0</span>
<span>elif</span> <span>old_value</span> <span>&gt;</span> <span>255</span><span>:</span>
    <span>new_value</span> <span>=</span> <span>255</span>
<span>else</span><span>:</span>
    <span>new_value</span> <span>=</span> <span>np</span><span>.</span><span>uint8</span><span>(</span><span>np</span><span>.</span><span>round</span><span>(</span><span>old_value</span> <span>/</span> <span>255.0</span><span>))</span> <span>*</span> <span>255</span>
</code></pre></div></div>

<p>With a much simper version:</p>

<div><div><pre><code><span>new_value</span> <span>=</span> <span>0</span> <span>if</span> <span>old_value</span> <span>&lt;</span> <span>128</span> <span>else</span> <span>255</span>
</code></pre></div></div>

<p>If we profile this optimized version we’ll see:</p>

<div><div><pre><code>$ python -m profila annotate -- dither2.py
Processed 758 images / sec
# Total samples: 713 (30.3% non-Numba samples, 2.2% bad samples)

## File `/home/itamarst/devel/sandbox/numba-profiling-article/dither2.py`
Lines 14 to 35:

  0.1% |     result = img.astype(np.int16)
       |     y_size = img.shape[0]
       |     x_size = img.shape[1]
       |     last_y = y_size - 1
       |     last_x = x_size - 1
       |     for y in range(y_size):
  0.3% |         for x in range(x_size):
  0.1% |             old_value = result[y, x]
  4.5% |             new_value = 0 if old_value &lt; 128 else 255
  2.0% |             result[y, x] = new_value
       |             # We might get a negative value for the error:
  5.5% |             error = np.int16(old_value) - new_value
  5.3% |             if x &lt; last_x:
 34.9% |                 result[y, x + 1] += error * 7 // 16
       |             if y &lt; last_y and x &gt; 0:
  3.6% |                 result[y + 1, x - 1] += error * 3 // 16
       |             if y &lt; last_y:
  6.0% |                 result[y + 1, x] += error * 5 // 16
       |             if y &lt; last_y and x &lt; last_x:
  4.5% |                 result[y + 1, x + 1] += error // 16
       |
  0.6% |     return result.astype(np.uint8)
</code></pre></div></div>

<p>As was the case in the <a href="http://ablwr.github.io/articles/optimizing-dithering/">original article</a>, our code now runs 3× as fast!</p>

<p>And this time we didn’t have to guess, we had a profiler to point us at the main bottleneck.</p>

<h2 id="the-limits-of-profiling">The limits of profiling</h2>

<p>While profiling is extremely helpful, it won’t always tell you everything you need to know to speed up your code.
To learn more about all of these issues, check out my <a href="http://ablwr.github.io/products/lowlevelcode/">upcoming book on writing high-performance low-level code</a>.</p>

<h3 id="limit-1-compiled-code-doesnt-always-match-the-source-code">Limit #1: Compiled code doesn’t always match the source code</h3>

<p>Consider the following example:</p>

<div><div><pre><code><span>@</span><span>njit</span>
<span>def</span> <span>add</span><span>(</span><span>arr</span><span>):</span>
    <span>result</span> <span>=</span> <span>np</span><span>.</span><span>empty_like</span><span>(</span><span>arr</span><span>)</span>
    <span>for</span> <span>i</span> <span>in</span> <span>range</span><span>(</span><span>len</span><span>(</span><span>arr</span><span>)):</span>
        <span>orig</span> <span>=</span> <span>arr</span><span>[</span><span>i</span><span>]</span>
        <span>orig</span> <span>+=</span> <span>123_000_000</span>
        <span>orig</span> <span>+=</span> <span>456_000</span>
        <span>orig</span> <span>+=</span> <span>789</span>
        <span>result</span><span>[</span><span>i</span><span>]</span> <span>=</span> <span>orig</span>
    <span>return</span> <span>result</span>
</code></pre></div></div>

<p>If we profile it, we get:</p>

<div><div><pre><code>## File `combo.py`
Lines 13 to 14:

  2.9% |         orig += 789
  7.5% |         result[i] = orig
</code></pre></div></div>

<p>Why is <code>orig += 789</code> listed, but not the other lines adding <code>123_000_000</code> and <code>456_000</code>?
Because thanks to compiler optimizations, they no longer exist in the compiled version as distinct operations.
We can for example inspect the generated assembly for the function and search for 789:</p>

<div><div><pre><code>&gt;&gt;&gt; for line in next(iter(add.inspect_asm().values())).splitlines():
...     if &#34;789&#34; in line: print(line)
...
        .long   123456789
        movl    $123456789, %edi
        movl    $123456789, %edx
</code></pre></div></div>

<p>The three added numbers (<code>123_000_000</code>, <code>456_000</code>, <code>789</code>) have been combined by the compiler into a single number (<code>123_456_789</code>) which presumably is being used with a single addition operation, instead of three.</p>

<h3 id="limit-2-you-need-a-mental-model-of-how-cpu-execution-works">Limit #2: You need a mental model of how CPU execution works</h3>

<p>Recall that in our optimized dithering function we saw the following profiling results:</p>

<div><div><pre><code>  5.3% |             if x &lt; last_x:
 34.9% |                 result[y, x + 1] += error * 7 // 16
       |             if y &lt; last_y and x &gt; 0:
  3.6% |                 result[y + 1, x - 1] += error * 3 // 16
       |             if y &lt; last_y:
  6.0% |                 result[y + 1, x] += error * 5 // 16
       |             if y &lt; last_y and x &lt; last_x:
  4.5% |                 result[y + 1, x + 1] += error // 16
</code></pre></div></div>

<p>Why is the first calculation so much more expensive than the later ones?
They seem to be doing more or less the same thing.</p>

<p>One hypothesis is instruction-level parallelism: the CPU is able to go ahead and speculatively execute the later code in parallel.
So the first line is expensive not because it’s any different, but because it’s <em>first</em>.
We can partially test this hypothesis by changing the order of the statements and profiling again.
Here’s the result:</p>

<div><div><pre><code>       |             if y &lt; last_y and x &gt; 0:
 20.3% |                 result[y + 1, x - 1] += error * 3 // 16
 14.2% |             if x &lt; last_x:
  8.8% |                 result[y, x + 1] += error * 7 // 16
       |             if y &lt; last_y:
  3.7% |                 result[y + 1, x] += error * 5 // 16
       |             if y &lt; last_y and x &lt; last_x:
  3.7% |                 result[y + 1, x + 1] += error // 16
</code></pre></div></div>

<p>Now the line <code>result[y, x + 1] += error * 7 // 16</code> has a much lower percentage of samples than in the previous version of the code, even though it’s running the exact same number of times and doing the exact same calculation.
The only thing that has changed is the order of execution.</p>

<p>A mental model of a CPU that just executes code linearly, with no parallelism, is not sufficient to understand these results.</p>

<h3 id="limit-3-faster-code-may-require-a-more-holistic-view">Limit #3: Faster code may require a more holistic view</h3>

<p>Seeing which lines of code are slow can be very helpful, but some optimizations are a result of rethinking the code more broadly.
For example, the final optimized version in the <a href="http://ablwr.github.io/articles/optimizing-dithering/">original article</a> cuts memory usage by two thirds, and also runs 50% even faster than the second version.
It does so by changing the structure of the algorithm, rather than just focusing on a single line or two of code.</p>

<h2 id="give-profila-a-try">Give Profila a try!</h2>

<p>Profila is a new project: I released it the same day I wrote this article.
So try it out, and please let me know about any bugs you find, your success stories, or any feedback at all, <a href="https://github.com/pythonspeed/profila/issues/new">in the GitHub issue tracker</a> or by email.</p>

  </div></div>
  </body>
</html>
